language: python
python:
  - "3.7"
node_js:
  - "12"
install:
  - node -v
  - pip install -r requirements.txt
  - pip install git+https://github.com/lux-org/lux-widget
script:
  - echo "successful build" 